### PR TITLE
fix custom deserializer not working with generic types

### PR DESCRIPTION
**Pull request by amoscatelli**
support for generic type and type variable deserialization with custom deserializer

Signed-off-by: Alessandro Moscatelli <alessandro.moscatelli@visiontech.cloud>

### CODE REVIEW

**Comment by amoscatelli** [comment]
I fixed ComponentMatcher where only Class was supported.
Without this fix custom deserializers were not used when deserializing ParameterizedTypes (for example Collection<something>).

I fixed branch 1.x but the same applies to 2.x.
Should I commit&push on there too ? Or are you going to merge fixes from 1.x to 2.x ? What do you want me to do ?

**Comment by amoscatelli** [comment]
This fixes https://github.com/eclipse-ee4j/yasson/issues/478

**Comment by amoscatelli** [comment]
@bravehorsie what do you think of this ?

**Comment by Verdent** [comment]
@amoscatelli I am sorry it took so long for me to get to this PR of yours. So far for me it looks OK. But may I ask you to create some tests which would test the newly added functionality? :-) Just to be sure it works as expected.

In terms of 2.x PR, well if it wouldn't bother you to add it there, it would be probably the best :-)

**Comment by amoscatelli** [comment]
Monday I will provide a Test that will check if custom deserializer is actually called using a generic type

;)

**Comment by Verdent** [comment]
Sure thing! Thank you :-)

**Comment by amoscatelli** [comment]
Regarding the 2.x merge, do you want me to do an actual MERGE from 1.x to 2.x OR do you want me to make a new single commit with only my changes to 2.x branch ?

**Comment by Verdent** [comment]
Create new PR with only just that one commit (or two including the tests)

Thank you very much.

**Comment by amoscatelli** [comment]
@Verdent ok I added the required test, I also made the pull request for the master branch

https://github.com/eclipse-ee4j/yasson/pull/480

**Comment by amoscatelli** [comment]
I hope you'll accept the pull soon
Let me know if you need something

**Review by Verdent — APPROVED** [review]
LGTM

**Comment by Verdent** [comment]
Thank you for doing the fix and test! :-)

**Pull request merged**
