### PR TITLE
Parse default methods in interface as properties

### LINKED ISSUE #99: Default methods from interface are ignored
Property defined within interfaces with the help of default methods shouln't be ignored.

This test fails:
```
public class DefaultMethodTest {

    public static interface Defaulted {

        default public String getGetterA() {return "valueA";}
    }

    public static class PojoWithDefault implements Defaulted {
    }

    @Test
    public void testWithDefault() {
        PojoWithDefault pojo = new PojoWithDefault();
        String result = jsonb.toJson(pojo);
        System.out.println("JSON: " + result);
        Assert.assertEquals("{\"getterA\":\"valueA\"}", result);
    }
}
```

ClassParser should handle such default methods.

### PR DESCRIPTION
**Pull request by maxencelaurent**
Issues
* fixes #99

### CODE REVIEW

**Comment by Verdent** [comment]
Looks good to me

**Comment by Verdent** [comment]
We have two requirements which are not fulfilled here:
1) Your commits need to be signed off.
2) Your email has to be ECA valid. That means that you have to sign Eclipse Contributor Agreement.

Please make sure that you meet both requirements above and then we will be able to merge your pull request.

**Comment by maxencelaurent** [comment]
1. done;
1. I already signed ECA long time ago. Did I miss something?

**Comment by Verdent** [comment]
Thank you for fast response:-) Everything looks OK now from my point of view. No, you didn't miss anything, but I just didn't have your email to be able to verify that you have signed it already. I mentioned it just to be sure you know about it.

**Comment by m0mus** [comment]
@Verdent @bravehorsie I'm OK to merge it after you folks tell me that it doesn't break any TCK tests.

**Pull request merged**
