### PR TITLE
FIX/345 : Serializing enums in maps keys issue

### PR DESCRIPTION
**Pull request by srius**
PR for Travis build and UT check only : I am unable to build yasson locally (issue with java.json module not found).

### CODE REVIEW

**Comment by srius** [comment]
Fix for #345 . PR ready.

**Comment by Tomas-Kraus** [comment]
It would be good to check whether deserialization works too. Code change looks good to me. I just shall not forget to put it into new version of sererializer I'm currently working on. So yours test is another one I shall pass. :)

**Comment by aguibert** [comment]
@Tomas-Kraus I tried to see if a Deserialization test worked locally, and noticed that deserialization of `EnumMap` does not work at all with Yasson. I think this was a gap that I overlooked between PR #315 and PR #295.

I am going to merge this PR since it is a good improvement, and will work on delivering support for deserialization of EnumMaps under issue #283

**Comment by Tomas-Kraus** [comment]
It would be great if you can fix it at least in old MapDeserializer class which is being used to build Map from JSON object.
MapEntriesArrayDeserializer is being called to deserialize Map from JSON array of Mapentries and it may have the same issue.

**Comment by aguibert** [comment]
We would only have to update MapEntriesArrayDeserializer if someone defined a `Map<EnumMap<?,?>,?>` (so the `EnumMap` is the key) right? If yes, I think this is a pretty unlikely scenario

**Pull request merged**
