### PR TITLE
Support for records added

### PR DESCRIPTION
**Pull request by Verdent**
Signed-off-by: David Kral <david.k.kral@oracle.com>

### CODE REVIEW

**Comment by Verdent** [comment]
Fixes #495

**Comment by lostiniceland** [comment]
Does this PR support Records without any empty constructors or addition annotations?
I would excect JSONB to support simple records like
```
record Foo(String a, int b) {}
```

**Comment by Verdent** [comment]
@XakepSDK It cannot process `@JsonbTypeAdapter` since it is not supported on parameter right now.

@lostiniceland in its current state it doesn't. I will think about it a bit. Possibly it might make sense to do. Thank you for that suggestion.

**Comment by Verdent** [comment]
@lostiniceland Hi, I have done some testing and I have to say, that I have completely forgot, that having `@JsonbProperty` is not even required in creators. Because of that, I can safely say, this feature you were asking about is supported. :-) I have even added one test to verify that.

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by lostiniceland** [comment]
Are there plans for a release so this feature can be integrated? The last release is a year old.
I would love to see this in Quarkus for our Kafka-DTOs.

**Comment by Verdent** [comment]
@lostiniceland The release with this feature has been done yesterday. :-)

**Comment by lostiniceland** [comment]
I see you published on Maven Central. Sorry for the fuzz: I was just following the Github release page which has 2.0.0 as the latest release.
https://github.com/eclipse-ee4j/yasson/releases

**Comment by Verdent** [comment]
No worries. I will update the release page also.

**Comment by lostiniceland** [comment]
@Verdent Would it be possible to backport this fix to the 1.x line?
Since 2.x includes the switch to the Jakarta namespace it is currently not possible to have proper record support for instance in Quarkus (see [#quarkus](https://github.com/quarkusio/quarkus/issues/22184)

**Comment by gabrielcampos** [comment]
Yes, it would be great to have this ported to the 1.x line.

**Comment by Verdent** [comment]
Hi guys, I am currently working on it. I am also doing some improvements into the overall record handling. It should be ready very soon :-)

**Comment by Verdent** [comment]
I have made an issue for you to be able to track it. #528

**Comment by lostiniceland** [comment]
I will have a look next week and add submit a PR.

**Comment by Verdent** [comment]
@gabrielcampos Yasson 1.0.11 and 2.0.4 are being released today to the maven central. Both contain improved record support.

**Pull request merged**
