### PR TITLE
Fixed serialization of Longs outside of IEEE 754 range.

### PR DESCRIPTION
**Pull request by bravehorsie**
Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

### CODE REVIEW

**Comment by bravehorsie** [comment]
Fixes https://github.com/javaee/jsonb-spec/issues/80

**Comment by cyberphone** [comment]
Hi Guys,
This was a quick fix!  However, looking into the pull request, this is probbly not exactly what I was looking for.

Having a variable serialization method for a specific data type will create interoperability issues. In the I-JSON mode, a long should (IMO) always be serialized in quotes.

**Comment by bravehorsie** [comment]
> Having a variable serialization method for a specific data type will create interoperability issues. 

JSONB spec defines, that only numbers outside of IEEE 754 range should be serialized as strings. From Java perspective this means only types supporting greater precision.

>In the I-JSON mode, a long should (IMO) always be serialized in quotes.

According to: https://tools.ietf.org/html/rfc7493#section-2.2 only numbers outside of IEEE 754 precision range should be serialized as strings. In case of Longs I interpret this as _"only Longs, that have its value outside of this range"_ are serialized as strings. Are you saying we should serialize all Long values as a String?

**Comment by m0mus** [comment]
@cyberphone Why do you think that all longs should be serialized as strings? For sure it will break compatibility with other clients.

**Comment by Verdent** [comment]
Looks good to me.

**Pull request merged**
