### PR TITLE
Update version to 1.0.7-SNAPSHOT

### PR DESCRIPTION
**Pull request by aguibert**
Version 1.0.6 has been released to Maven Central so we need to update for the next development iteration

### CODE REVIEW

**Comment by aguibert** [comment]
@Verdent can you please review

**Comment by aguibert** [comment]
hi @Verdent or @m0mus can one of you please review?

**Comment by Verdent** [comment]
I have found out why your TCKs are failing. Could you please update GF bundle link in tck.sh to the following?
repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/5.1.0/glassfish-5.1.0.zip

**Comment by aguibert** [comment]
thanks for checking on that @Verdent, I've updated the URL but that didn't fix it alone. Maven Central now requires HTTPS so I also had to update the URL to be `https://` and then allow an insecure HTTPS connection on the `wget` call (it seems that maven central doesn't have a well know certificate)

**Comment by Verdent** [comment]
Good point. :-)

**Comment by aguibert** [comment]
@Verdent I think you forgot to approve the code review? I can't merge the PR until you do so

**Comment by Verdent** [comment]
Well I did not :-) I am waiting for your build to pass. Since your PR is not fully passing yet, I did not give it approval. Update copyright please and I believe, that it will pass everything now.

**Comment by aguibert** [comment]
ah, I forgot to run the delivery checks after doing the tck.sh cleanup -- its fixed now

**Pull request merged**
