### PR TITLE
Do not implicitly close java.io.Writer on toJson

### PR DESCRIPTION
**Pull request by aguibert**
For #389 in the 1.X branch

@Verdent please review. Once this PR is approved I will port the same changes to master

### CODE REVIEW

**Comment by amihaiemil** [comment]
@Verdent Can you please review this PR? This bugfix is very important for us, it would be nice if it could be released asap. Thank you! 

cc: @aguibert

**Comment by Verdent** [comment]
Ah totally missed that. Thanks for pinging me.

**Comment by aguibert** [comment]
thanks for reviewing @Verdent, had to do some extra changes to make checkstyle/coypright plugins happy. Will merge once the CI build completes green

**Comment by Verdent** [comment]
@aguibert sure :-)

**Pull request merged**
