### PR TITLE
Don't fail when using ResourceBundle.Control in JPMS named module.

### PR DESCRIPTION
**Pull request by bravehorsie**
Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

### CODE REVIEW

**Comment by bravehorsie** [comment]
Merging this based on comments in #195

**Comment by psakar** [comment]
May I suggest to update surefire plugin to latest version so it contains fix for https://issues.apache.org/jira/browse/SUREFIRE-1262 - that way this issue should be visible in failing tests

**Comment by psakar** [comment]
Most probably following would be handy as well (probably wrapped in profile  for java 11+):

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    
                    <argLine>
                        --add-opens java.base/java.lang=org.eclipse.yasson
                        --add-opens java.base/java.util=org.eclipse.yasson
                        --add-opens=org.eclipse.yasson/org.eclipse.yasson.adapters.model=ALL-UNNAMED
                        --add-opens=org.eclipse.yasson/org.eclipse.yasson.internal.cdi=ALL-UNNAMED,java.naming
                        --add-opens=org.eclipse.yasson/org.eclipse.yasson.internal.serializer=ALL-UNNAMED
                        --add-opens=org.eclipse.yasson/org.eclipse.yasson.serializers.model=ALL-UNNAMED
                        --add-opens=org.eclipse.yasson/org.eclipse.yasson=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>

**Comment by bravehorsie** [comment]
>                
                    --add-opens java.base/java.lang=org.eclipse.yasson
                    --add-opens java.base/java.util=org.eclipse.yasson
                    --add-opens=org.eclipse.yasson/org.eclipse.yasson.adapters.model=ALL-UNNAMED
                    --add-opens=org.eclipse.yasson/org.eclipse.yasson.internal.cdi=ALL-UNNAMED,java.naming
                    --add-opens=org.eclipse.yasson/org.eclipse.yasson.internal.serializer=ALL-UNNAMED
                    --add-opens=org.eclipse.yasson/org.eclipse.yasson.serializers.model=ALL-UNNAMED
                    --add-opens=org.eclipse.yasson/org.eclipse.yasson=ALL-UNNAMED

java.base already exports `java.lang` and `java.util`, why do we need to --add-opens for those? Yasson doesn't hack into JDK internal API's.

same for Yasson packages to ALL-UNNAMED, what is the reason to do so? Doesn't new version of surefire --patch-module org.eclipse.yasson with test classes before run?

Good idea to bump surefire version, there are more things in POM that could be updated due to better JPMS support.

**Comment by psakar** [comment]
I have to add those to pass all failing tests once I've bumped up the surefire version while rebuilding internally 1.0.2 release with java 11 for JBoss EAP (based upon Wildfly).
The best I can suggest it to bump up the version and run the tests, you will see the reason for those --add-opens in exceptions for failed tests.
Please ignore commented line at the beginning of configuration, sorry for that, should not be here, I've forget to remove it, I'm sorry for that.
Also sorry for not raising proper issue / PR, we are just a bit under time presure with release ATM

**Comment by bravehorsie** [comment]
The only thing that looks reasonable is that POJO's, which are accessed by reflection in Yasson are put to classpath and so end up in ALL-UNNAMED, while Yasson is put to module path. Either both should be put on CP or MP to avoid extra --add-opens for unnamed module.

**Pull request merged**
