### PR TITLE
Issue 342: Custom De-Serialization Bug

### PR DESCRIPTION
**Pull request by rmartinc**
Fix for issue #342 in master branch. Just calling respective methods to do the getObject and getArray. Added a test for parsing an object.

Fix for branch 1.x. PR for master is https://github.com/eclipse-ee4j/yasson/pull/481.

### CODE REVIEW

**Review by Verdent — APPROVED** [review]
LGTM

**Comment by ivassile** [comment]
@Verdent Is it possible to tag yasson 1.0.9 with this fix? We need to incorporate this fix in JBoss EAP. Your help would be much appreciated. Thanks!

**Comment by Verdent** [comment]
@ivassile Sure, we plan it soon. I cant really say when since we didn't come up with the date, but I think sometime next week. Is that OK with what you need? :-)

**Comment by ivassile** [comment]
@Verdent Next week is fine. Thanks!

**Comment by Verdent** [comment]
Hi @ivassile , yasson 1.0.9 and 2.0.2 is out :-)

**Comment by rmartinc** [comment]
@Verdent Yeah! We already saw it yesterday. Thanks a lot!

**Comment by ivassile** [comment]
@Verdent I saw it yesterday and started the upgrade in EAP. Thanks!

**Pull request merged**
